server:
  addr: ":5500"
mysql:
  dsn: "root:123456@tcp(127.0.0.1:5506)/video_service?charset=utf8mb4&parseTime=True&loc=Local"
redis:
  addr: "127.0.0.1:5509"
etcd:
  addr: ""
  
prometheus:
  global:
    scrape_interval: 60s
  scrape_configs:
    - job_name: 'sync_service'
      metrics_path: /metrics
      static_configs:
        - targets: ['sync_service:5500']
