server:
  addr: ":6661"
mysql:
  dsn: "root:123456@tcp(mysql:3306)/video_service?charset=utf8mb4&parseTime=True&loc=Local"
redis:
  addr: "redis:6379"
etcd:
  addr: "etcd:2379"
  
prometheus:
  global:
    scrape_interval: 60s
  scrape_configs:
    - job_name: 'sync_service'
      metrics_path: /metrics
      static_configs:
        - targets: ['sync_service:6661']
